import './global.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
     <body>
       <div className="flex h-screen justify-center items-center max-w-2xl mx-auto mt-3">
        {children}
       </div>
     </body>
    </html>
  )
}
